version: '3'

services:
    workenv:
        hostname: 'docker-workenv'
        image: workenv
        build: .
        volumes:
            - ../:/volume
        ports:
            - "22:22"
            - "8000:8000"
        restart: always
